# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# My theme
ZSH_THEME="carvil"

# Load plugins
plugins=(git osx gem rbenv brew)

# oh-my-zsh configs
source $ZSH/oh-my-zsh.sh

# Using vim as default editor
export EDITOR="vim"
bindkey -v

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# smart cd
setopt AUTO_CD

# git alias
alias gco='git co'
alias gci='git ci'
alias grb='git rb'
alias glg="git log --graph --pretty=format':%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset'"

# bundler alias
alias be='bundle exec '

# github username
export GITHUB_USER="carvil"

path=(
  /usr/local/opt/rbenv/shims
  /usr/local/{bin,sbin}
  /usr/local/heroku/bin
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

eval "$(rbenv init -)"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:/usr/local/share/npm/bin:$PATH"
